#                                  NumPy exercises

## Array creation

In [ ]:
#Import NumPy library
import sys
import numpy as np

In [3]:
#1 Create a numpy array of size 10, filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#2 Create a numpy array with values ranging from 10 to 49 and set its datatype to float
a = np.arange(10,50 , dtype=float)
print(a)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [11]:
a.dtype

dtype('float64')

In [14]:
#3 Create a numpy matrix of 2*2 integers, filled with ones.
matrix = np.ones((2,2), dtype=int)
print(matrix)

[[1 1]
 [1 1]]


In [15]:
#4 Create a numpy matrix of 3*2 float numbers, filled with ones.
matrix1 = np.ones((3,2), dtype=float)
print(matrix1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
#5.Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. 
#hint: search the function np.ones_like( ) )
X = np.array([[9,3],[4,8]])
print(X)
Y = np.ones_like(X)
print(Y)
Y.dtype

[[9 3]
 [4 8]]
[[1 1]
 [1 1]]


dtype('int32')

In [31]:
#6 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros
Z = np.zeros_like(X)
print(Z)
Z.dtype

[[0 0]
 [0 0]]


dtype('int32')

In [33]:
#7 Create a numpy matrix of 4*4 integers, filled with fives

x_matrix = np.full([4,4],5, dtype=int)
print(x_matrix)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [37]:
#8 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens
x_matrix = np.full([4,4],5, dtype=int)
Ymatrix = np.full_like(x_matrix, 7)
print(Ymatrix)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [53]:
#9 Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
#a
i_matrix =np.array([[1,0,0],[0,1,0], [0,0,1]])
print("One way", i_matrix)

#b
identity_matrix = np.identity(3)
print("second way",identity_matrix)

#c
identity_matrix = np.eye(3)
print("third way" , identity_matrix)

One way [[1 0 0]
 [0 1 0]
 [0 0 1]]
second way [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
third way [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
#10 Create a numpy array, filled with 3 random integer values between 1 and 10

random = np.random.randint(10, size=3)
print(random)

[6 5 3]


In [58]:
#11 Create a 3*3*3 numpy matrix, filled with random float values
random_2 = np.random.rand(3,3,3)
print(random_2)

[[[0.53477302 0.31187331 0.61015294]
  [0.94831182 0.71952588 0.41709439]
  [0.17847097 0.7940066  0.78567664]]

 [[0.0094916  0.00210303 0.19826726]
  [0.8060838  0.29500072 0.11106534]
  [0.20043684 0.73411029 0.0406565 ]]

 [[0.97781872 0.01971422 0.15231718]
  [0.87692707 0.12574279 0.1721557 ]
  [0.94415769 0.4714889  0.26972953]]]


In [60]:
#12 Create a numpy array with numbers from 1 to 10
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [61]:
#13 Create a numpy array with the odd numbers between 1 to 10
array_odd = np.arange(1,10, step=2)
print(array_odd)

[1 3 5 7 9]


In [62]:
#14 Create a numpy array with numbers from 1 to 10, in descending order.
desc_array = np.flip(np.arange(1,11))
print(desc_array)

[10  9  8  7  6  5  4  3  2  1]


In [68]:
#15 Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Array indexing

In [70]:
#1 Given the X numpy array, show its first element
X = np.array(['A','B','C','D','E'])

X[0]


'A'

In [71]:
#2 Given the X numpy array, show its last element
X = np.array(['A','B','C','D','E'])
X[-1]


'E'

In [73]:
#3 Given the X numpy array, show its first three elements
X = np.array(['A','B','C','D','E'])

X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [74]:
#4 Given the X numpy array, show all middle elements
X = np.array(['A','B','C','D','E'])

X[1:4]

array(['B', 'C', 'D'], dtype='<U1')

In [75]:
#5 Given the X numpy array, show the elements in reverse position.
X = np.array(['A','B','C','D','E'])
np.flip(X)

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [85]:
#6 Given the X numpy array, show the elements in an odd position.
X = np.array(['A','B','C','D','E'])
X[1::2]

array(['B', 'D'], dtype='<U1')

In [87]:
#7 Given the X numpy matrix, show the first row’s elements.
X = np.array([ [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

X[0][:]

array([1, 2, 3, 4])

In [88]:
#8 Given the X numpy matrix, show the last row elements.
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

X[-1][:]

array([13, 14, 15, 16])

In [89]:
#9 Given the X numpy matrix, show the first element on first row
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]])

X[0][0]

1

In [90]:
#10 Given the X numpy matrix, show the last element on last row.
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

X[-1][-1]

16

In [96]:
#11 Given the X numpy matrix, show the first two elements on the first two rows.
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

X[:2, :2]


array([[1, 2],
       [5, 6]])

In [98]:
#12 Given the X numpy matrix, show the last two elements on the last two rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

X[-2:, -2:]


array([[11, 12],
       [15, 16]])

## Array manipulation

In [103]:
#1 Convert the given integer numpy array to float
X = np.array([-5, -3, 0, 10, 40])
float_x = X.astype(float)
print(float_x)

[-5. -3.  0. 10. 40.]


In [108]:
#2 Reverse the given numpy array (first element becomes last) through indexing
X = np.array([-5, -3, 0, 10, 40])
X[::-1]


array([40, 10,  0, -3, -5])

In [113]:
#3 Given the X numpy array, set the fifth element equal to 1
X = np.zeros(10)
X[4]=1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [115]:
#4 Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

X[-1] = 1
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [117]:
#5 Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]])

sum = X + 5
print(sum)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
